# apiVersion: networking.k8s.io/v1beta1 # for k3s < v1.19
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elasticsearch
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    traefik.ingress.kubernetes.io/router.tls: "false"
spec:
  rules:
  - http:
      paths:
      - path: /elasticsearch
        pathType: Prefix
        backend:
          service:
            name: quickstart-es-http
            port:
              number: 9200